In [4]:
# 1
import numpy as np
e = np.array([[1,2,3,4],[3,4,5,6]])
print(e)

[[1 2 3 4]
 [3 4 5 6]]


In [7]:
# 2
x = np.zeros((2,3))
y = np.ones((2,3))

print(x)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 3
a = np.array([[1,2], [4,5]])
b = np.array([[1,2], [1,3]])
a * b

# array([[ 1,  4],      # 1행 1열, 2행 1열 / 1행 2열 , 2행 2열 ,,, 곱해짐
     #  [ 4, 15]])


array([[ 1,  4],
       [ 4, 15]])

In [13]:
# 4
a = np.array([[1,2], [4,5]]).transpose
b = np.array([[1,2], [1,3]]).transpose
print(a)
print(b)


<built-in method transpose of numpy.ndarray object at 0x000001AB66AF9E30>
<built-in method transpose of numpy.ndarray object at 0x000001AB65D8FC30>


In [ ]:
import numpy_financial as npf

cf
array([[-400, -200, 300, 300, 300]])